# Generated by Django 5.0.4 on 2024-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('physical_quantity', models.CharField(max_length=50)),
                ('metric', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
        ),
    ]
