# Generated by Django 5.0.4 on 2024-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_entitydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitydata',
            name='entity_id',
            field=models.IntegerField(unique=True),
        ),
    ]
